### ISSUE TITLE
Following naming convention

### ISSUE THREAD

**Issue by sobolevn** [MatteoGabriele/vue-analytics#1]
Hello, thanks for your library, it is working pretty smooth: https://github.com/wemake-services/razgrebaem.ru/blob/master/src/store/analytics.js

But I have a strong feeling that naming convention is not right. What are my reasons:

1. `$` prefix on `Vue` instance. As I know it, in the `vue`-world the following convention is followed: any plugins, which are registered, bind as-is to the `Vue` instance but add `$` prefix to the `this`, not to overwrite anything. Here are the examples: http://router.vuejs.org/en/api/route-object.html, https://vuex.vuejs.org, https://github.com/pagekit/vue-resource

2. It is named `track`, but why not `ga`?

Anyway, great work!

**Comment by MatteoGabriele** [comment]
Hi @sobolevn,  

I was actually thinking about adding all methods also in the prototype object, to make them available in every component without importing `Vue` itself: so definitely gonna add it 👍  

The name `track` it's just because makes it more readable in an actual line of code. 
I see `this.$track.page` and I immediately know what's going on.
`ga` instead doesn't have any semantic for me. Does it make sense?

**Comment by sobolevn** [comment]
My opinion is that `ga` is a well-known acronym. I am not sure about `track` actually.

**Comment by MatteoGabriele** [comment]
I will add an alias for `ga` as well.

Thanks for the suggestions :)

**Comment by MatteoGabriele** [comment]
I forgot to add in the description of the commit that also the first point is being added, but it's there 🚀
