### ISSUE TITLE
All [Vue warn] message sand JS errors dissapeared

### ISSUE THREAD

**Issue by JoseOspina** [MatteoGabriele/vue-analytics#112]
I am using "vue-analytics": "^5.9.0"

When I add 
```
Vue.use(VueAnalytics, {
   id: 'MY ID HERE'
})
```

to `main.js`, I stop seeing any `[Vue warn]` or Javascript errors while developing.

Its the same in Chrome and Firefox

**Comment by MatteoGabriele** [comment]
hi @JoseOspina 
just adding your ID doesn't mean that the plugin is tracking something: you need to enable auto-tracking or start tracking yourself.

For what concerns error handling, you should update to the last version:
that bug is already fixed ( see https://github.com/MatteoGabriele/vue-analytics/commit/500993c )

**Comment by JoseOspina** [comment]
Thanks @MatteoGabriele, maybe it is possible to make it clear in the Getting Started page, that adding the ID is not enough.
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/installation.md

**Comment by MatteoGabriele** [comment]
I gave that for grunted. In the readme there are also 2 articles I wrote about how to start and tips & tricks.
I might add them also to the installation page then :)

thanks for your feedback
