### ISSUE TITLE
Need help - unable to get vue-analytics working

### ISSUE THREAD

**Issue by manastalukdar** [MatteoGabriele/vue-analytics#122]
Implementation [here](https://github.com/manastalukdar/manastalukdar.github.io/blob/master/website/src/main.js).

I do not see any data in my Google Analytics dashboard. I have looked through [this](https://github.com/MatteoGabriele/vue-analytics/issues/51) and [this](https://github.com/MatteoGabriele/vue-analytics/issues/82), and tried some things as suggested there to no avail.

Would appreciate any pointers as to what I may be doing wrong.

**Comment by MatteoGabriele** [comment]
The installation is correct. it could just be some issues with GA, especially if it's a new account.
I'm sorry but events are fired correctly, the plugin works.

let me know in a couple of days of usage if it is fixed, otherwise, create a repository with the error you think the plugin has and I'll have a look.

thanks for your feedback and good luck :)

**Comment by manastalukdar** [comment]
@MatteoGabriele Thanks. Everything works now. For some reason, GA just took some time to start getting data. Perhaps, as you said, because it was a new account.

**Comment by MatteoGabriele** [comment]
@manastalukdar yeah I receive a lot of ticket about this scenario and 99% of the time, if the setup of the plugin is good, it's just matter of waiting a bit because it's a new account :)

glad that is working now
