### ISSUE TITLE
Tracker name

### ISSUE THREAD

**Issue by antonreshetov** [MatteoGabriele/vue-analytics#167]
I'm sorry, but how can I add the name of the tracker
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#name

**Comment by MatteoGabriele** [comment]
hi @antonreshetov 
you can't: I generate that automatically from the domain ID as a unique identifier, whenever an array of ids is passed, otherwise there's no need for a tracker name.

Usually the tracker is useful when dealing with multiple domains so normally you would send an event like this `ga('send', 'event', ...)`, but when you add multiple ids, that calls will become like this `ga('send.domain_key_1', 'event', ...)` and so on for every id you have entered.

**Comment by MatteoGabriele** [comment]
I will close this ticket for inactivity, but feel free to re-open it with more info
