### ISSUE TITLE
"Location" is always the first loaded page

### ISSUE THREAD

**Issue by hmaesta** [MatteoGabriele/vue-analytics#170]
I am using vue-analytics with debug enabled.

```js
import router from './router'

Vue.use(VueAnalytics, {
  id: 'UA-XXXXX-X',
  router,
  debug: { enabled: true }
});

new Vue({
    el: '#app',
    router,
    store,
    render: h => h(App)
});
```

I noticed on console that `location` is always **the first loaded page**.

So, if user comes to my website directly by a link (`http://localhost/my-account/`, for example), `location` is always `http://localhost/my-account/`

`page` is changing – thats fine.
But `location` shouldn't always be my domain? (`http://localhost/`, in this case).

<img width="578" alt="screen shot 2018-10-12 at 11 32 45" src="https://user-images.githubusercontent.com/741969/46875778-021dad80-ce13-11e8-899e-f5830a092266.png">

On Analytics everything looks fine, so I guess this is an expected behavior, but I am still confused.

### Expected behavior

`location: http://localhost/`

### Actual behavior

`location: http://localhost/login/`
`location: http://localhost/my-account/`
(etc)

### Environment

- vue-analytics@5.16.0
- vue@2.5.17
- macOS Mojave 10.14 (18A391)
- Chrome 69.0.3497.100

**Comment by MatteoGabriele** [comment]
Hi @hmaesta 
I think that location is automatically detected by Google Analaytics, the plugin just fires this event options 

```js
set('page', page)
query('send', 'pageview', '/homepage')
```
only changes if you have a `base` option in your router instance, then that's prepended as well and probably that's the case for you.

if you have a `base` option but your don't want to prepend it to your analytics events, you can simply turn that off in with this option

```js
Vue.use(VueAnalytics, {
  id: 'UA-XXXXX-X',
  router,
  autoTracking: { prependBase: false },
  debug: { enabled: true }
});
```

let me know if this helped, otherwise try to be more specific or create an example that I can check

thanks

**Comment by hmaesta** [comment]
Hey Matteo. Thank you for replying. 
I do not use a `base` option. My app runs on root.

I am checking Analytics reports since I installed `vue-analytics` and everything looks fine – as any other website. So, I don't think this `location` detail should be a headache.

Perhaps this issue can be useful for other people that bothers with `location`: at least for me, there is no problem at all on reports, so maybe you should ignore that.

Thank you for this great tool, @MatteoGabriele.
