### ISSUE TITLE
[Q] How to set/send custom dimensions variables?

### ISSUE THREAD

**Issue by neorganic** [MatteoGabriele/vue-analytics#174]
My custom dimensions don't seem to be passed to GA - judging by tag manager, chrome dev tools requests query strings params or by the GA web app itself.

I've tried setting the custom params like:
```
new Vue({
  router,
    mounted () {
        console.log('triggered')
        Vue.$ga.set('role', 'test role')
        Vue.$ga.set('billing', 'test billing')
    },
  store,
  render: h => h(App)
}).$mount('#app')
```

also
```
new Vue({
  router,
  store,
  render: h => h(App),
  mounted () {
    set(role : this.user ? this.user.role : null)
    set(   subscription_type: JSON.parse(localStorage.vuex).subscription.currentPlanName
  }
}).$mount('#app')
```

when  `set` is being imported ```import { set } from 'vue-analytics'```

also : 
```
Vue.use(VueAnalytics, {
  id: 'UA-12random-keysasdads1-1',
  set: [
    {
      field: 'role', value: 'role value'
    }, {
      field: 'billing', value: 'billing value'
    }
  ]

})
```
But all resulted in zero effect and zero console errors.

The event itself works well - I am using various events all other my app via a global method:

```
Vue.mixin({
  methods: {
    dispatchEvent: (category, action, label, value = 0) => event(category, action, label, value)
  }
})
```

and then in the app e.g.:
```
 this.dispatchEvent('splash', 'scroll', 50)
```

But my dimensions are never attached to the events - any help? :)

**Comment by MatteoGabriele** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets these are the official API examples for custom dimensions.

always set the `debug.enabled` to `true` in your plugin setup to see if the informations are sent: if it's all sent in the debug tool, then I cannot make any difference.

if the issue persist and you can re-create it, then I suggest you to create a simple public repo with a basic setup of vue-cli and link it here to me to check

cheers :)

**Comment by rubenheymans** [comment]
where can you find these custom variables in analytics? and how do you fetch them using the analytics api? I can't find anything in the docs

**Comment by boicetomlin** [comment]
The custom vars can be viewed in analytics under Audience -> custom -> custom variables.  I also see no way to call the __setCustomVar method.  it's not an event.  it's not a page view.  set method does not seem to work because the __setCustomVar method takes four arguements:[ index, name, value, opt_scope].

https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingCustomVariables

Unless I'm missing something the ability to use this feature of analytics is not available with this plugin.

Is there a way to manually query and send this data maybe?
