### ISSUE TITLE
QUESTION, Cant find analytics.js being loaded... ?

### ISSUE THREAD

**Issue by drosendo** [MatteoGabriele/vue-analytics#175]
Im sorry Im missing something here..

```
import Vue from 'vue';
import VueAnalytics from "vue-analytics";

Vue.use(VueAnalytics, {
  id: "UA-XXXXXXX-X",
  ecommerce: {
    enabled: true,
    enhanced: true
  },
  debug: {
    enabled: false,
    trace: false,
    sendHitTask: false
  }
});

```

With debug TRUE I can see on my console the  $this.$ga.event and also the this.$ga.ecommerce.addTransaction getting fired, but this ones (this.$ga.ecommerce) are not showing up on the google analytics (I have ecommerce turned on at analytcs). the  $this.$ga.event show up on analytics.

What I dont find is where is the analytics.js loaded? I cant find it anywhere on the page being called. Do I still have to add the script manually? 

Thanks,
David

**Comment by MatteoGabriele** [comment]
No you don't have to add any scripts.
When debug is turned on, analytics.js is not loaded because I load the official debug script from Google Analaytics called analytics-debug.js.

your data is not on Google Analytics website because you have `sendHitTask` on false. What this check does is only shows you in your local environment that events are fired, but it doesn't really send them to Analytics.

if you want to see your local stats online, just remove that property, which is `true` by default.

Everything you see in the console will end up in your Analytics account, if doesn't do that is or because of the `sendHitTask` false or for other reasons that I cannot control 

I hope I'll made things more clear :)

cheers

**Comment by drosendo** [comment]
Awsome, thanks for the clarification,will try it.

Cheers,
Great work!
