### ISSUE TITLE
Single Page Application tracking

### ISSUE THREAD

**Issue by SamuelRacine** [MatteoGabriele/vue-analytics#287]
Hi there,

I need to implement page tracking in my nuxt typescript SPA.

According to [this GA documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications), in order to do proper page tracking for SPA you should make those 2 calls:
```
ga('set', 'page', '/new-page.html');
ga('send', 'pageview');
```

Therefore the first call for the set page would translate to something like this right? :
`this.$ga.page('/thePageIwantToTrack')`

Now for the second call that I should do, I can't find a send function. Or maybe `this.$ga.page` is taking care of this automatically?

How can I trigger `ga('send', 'pageview');` using the plugin?

Thanks a lot,

Sam

**Comment by MatteoGabriele** [comment]
Sorry for the delay, if you are manually tracking then you can use `query('send', 'pageview')` or just use the vue-analytics built-in router tracking that does it for you automatically.

Strange that I never exposed that method. It's probably because most of the time developers use the automatic tracking system

**Comment by SamuelRacine** [comment]
Hi there,

It turns out that it's working fine without the `ga('send', 'pageview');`.

Best regards,

Sam
