### ISSUE TITLE
Cannot use 'in' operator to search for 'currentRoute' in path sent...

### ISSUE THREAD

**Issue by nishal** [MatteoGabriele/vue-analytics#53]
Not sure whats going on here. When running locally if I somehow manage to get 'currentRoute' initialised, calls to this.$ga.page(path) work fine. But when I deploy, I get the following error when I call this.$ga.page(path):

TypeError: Cannot use 'in' operator to search for 'currentRoute' in <path I sent as String, e.g. "/project">

I'm manually tracking each page hit.

**Comment by nishal** [comment]
I've managed to get a work around for now, sending the following object seemed to work ok:
{
    page: '/project',
    title: 'project',
    location: window.location.href
}

Not sure why the simpler construct with sending a string doesn't throws an error.

**Comment by MatteoGabriele** [comment]
@nishal thanks a lot for your feedback.
I really need to write tests to avoid these errors.

The fix is published with 4.3.1

**Comment by MatteoGabriele** [comment]
Before I was doing that check looking at the `value` constructor name, but when code is minified and mangled, name of the constructor changes and so that check fails.

To check if you are passing a route or not, i need to know if you are a router object: so I check if you have the `currentRoute` property.

It fails because you can check that against a string.

Very stupid error 😄

**Comment by nishal** [comment]
Thanks @MatteoGabriele  for the quick turn around.
