### ISSUE TITLE
Ecommerce Tracking

### ISSUE THREAD

**Issue by MadReal** [MatteoGabriele/vue-analytics#70]
What is the approach to tracking ecommerce events? I've tried different set ups and I always get an error.

I've imported the ecommerce plugin like so:

```
Vue.use(VueAnalytics, {
    id: TEST_ENV,
    router,
    ready() {
        // require the ecommerce plugin
        Vue.$ga.require('ecommerce')
    }
})
```

I've created a module in the store with the action:

```
    actions: {
        gaOrderCompleted({ commit }, order) {
            // send google e-commerce data
            order.items.forEach(itemBought => {
                this.$ga('ecommerce:addItem', {
                    'id': order.id, // Transaction ID. Required.
                    'name': itemBought.beat_name, // Product name. Required.
                    'sku': itemBought.sku, // SKU/code.
                    'category': itemBought.category, // Category or variation.
                    'price': itemBought.price, // Unit price.
                    'quantity': '1' // Quantity.
                })
            })
            this.$ga('ecommerce:addTransaction', {
                'id': order.id, // Transaction ID. Required.
                'revenue': order.total_payed // Grand Total.
            })
            this.$ga('ecommerce:send')
        }
    }
```

and I get an error. I've also tried Vue.VueAnalytics(...), Vue.ga(...), VueAnalytics.ga(....), Vue.$ga.ecommerce(...)

always get an error along these lines: __WEBPACK_IMPORTED_MODULE_0_vue__.default.$ga.ecommerce is not a function

How do I set this up?
Thanks

**Comment by MatteoGabriele** [comment]
Hi @MadReal 
thanks for you feedback!

First thing first: you can't use `this` inside a Vuex store module because the scope is totally different from a Vue component.
When you are inside a Vue component `this` refers to its instance that inherits the Vue prototype object: that object has all plugin methods.
Another place where methods are shared is the Vue instance itself as you can see in this piece of [code](https://github.com/MatteoGabriele/vue-analytics/blob/master/src/index.js#L15) from the plugin source.

Second `$ga` it's an object, not a function. I should probably make a list of those available in another part of the guide :)

Google Analytics api is pretty huge and I couldn't cover everything (but I am slowly doing that )
For this reason whenever you don't find a method described in the guide, means that it doesn't exist and you have to use the `query` method, which simply give you access to the entire api.

check this page [here](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/custom-methods.md)

For what you have to do I believe that you just need something like 
```js
Vue.$ga.query('ecommerce:addItem', {})
```
but be sure to install VueAnalytics before you install Vuex or all methods could still be not present.

I hope that the answer helped you enough

**Comment by MadReal** [comment]
Yes this worked! Thanks very much for the fast reply and awesome plugin

**Comment by MatteoGabriele** [comment]
Nice to hear that and thanks for your feedback.
I might going to add the e-commerce methods later today

**Comment by MatteoGabriele** [comment]
@MadReal I've added new ecommerce features with the v5.4.0
check the documentation if you're interested 


cheers

**Comment by MadReal** [comment]
Great! Thanks
