### ISSUE TITLE
Tracking events outside the scope of a component

### ISSUE THREAD

**Issue by paumoreno** [MatteoGabriele/vue-analytics#75]
Hi!

I don't know if I'm missing something, but I haven't found the way to track an event outside the scope of a component (e.g. in my Vuex store).

I think that the [documentation](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/event-tracking.md) assumes we're inside a component. How can I track an event when I don't have access to `this.$ga`?

Thanks!

**Comment by MatteoGabriele** [comment]
Even though I don't suggest to use it inside a vuex store, you could just use the Vue instance by importing vue itself in your file

```js
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
   actions: {
     foo () {
        Vue.$ga.event({ ... })
     }
   }
})
```

**Comment by nicooprat** [comment]
Why do you think it's not a good idea to track an event inside an action?

Looks like pretty solid to track it here instead of the element itself, on the click event for example: it could be triggered somewhere else in the future, and the GA event wouldn't be tracked.

**Comment by MatteoGabriele** [comment]
Because the purpose of Vuex store is to handle the state of your application: not to track information for Google Analytics.

Every part of your application should do _only one thing_: it's called separation of concerns.
If you start spreading functionalities everywhere you will never know exactly where to find your code.

This is just how I usually code, not really a religion :)

**Comment by nicooprat** [comment]
Understood, but Vuex actions (not mutations) seem to be a good *central* place to trigger these events. How/where would you rather do this?

**Comment by MatteoGabriele** [comment]
well vuex actions need to dispatch a mutation: nothing else :)

I would just track a click event right where it happens, so when you're looking for it, it won't take you extra time to remember where you did it: it's where it belongs.

If you need to centralize your tracking system because you are maybe writing the same thing multiple times, you can use the `command` object in the configuration object, even maybe combined with the v-ga directive.

you can find something [here](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/v-ga.md). Could be useful.

I can suggest you also to take a look at this [video](https://www.youtube.com/watch?v=pSdp92Up8O8) about single component responsibility. It's a pattern that can be used everywhere and maybe can answer some of your questions :)

**Comment by nicooprat** [comment]
Didn't see this `command` thing, looks perfect, thanks!
