### ISSUE TITLE
Dynamic Trackers

### ISSUE THREAD

**Issue by wannymiarelli** [MatteoGabriele/vue-analytics#78]
What if i need to track dynamic UA-codes, let's say i have to make a http request to get the list of ids to track

tracking.js
```
import Vue from 'Vue'
import VueAnalytics from 'vue-analytics'
// we must know which ones must be traked

axios.get('...').then(response => {
  Vue.use(VueAnalytics, {
    id: response.data.trackers // ['UA-XXX-A', 'UA-XXX-B']
  })
})
```
is this one a good idea? Do you see any issue?
I was thinking that there might be problems understanding when the plugin is actually active.

**Comment by MatteoGabriele** [comment]
Hi @wannymiarelli 
unless you bootstrap the application after the same http request, you will encounter some issues with that because probably you will call some plugin methods that are not installed yet or you will miss several hits to Analytics.

To achieve this I will need to accept a Promise as a value of the `id` property.
The Promise will the return a string, in case of a single id, or an array of strings in case of multiple tracking ids.

**Comment by wannymiarelli** [comment]
@MatteoGabriele Okay, for now i will bootstrap after the request, we have a single app distributed to all of our customers, based on the parameters given in the url we load the UI Data, it would be good to have support for promises in the initial method.
Would like to help with a PR in the next days.

**Comment by MatteoGabriele** [comment]
Now that I see the code again, making the ID a Promise is quite a refactor.
The issue is not waiting until it's resolved, because I could just add that to the queue of promises I have already, but I want to be able to track event meanwhile I'm waiting your http request to be done and it's not really easy right now.

**Comment by MatteoGabriele** [comment]
But please drop the PR when you have time: maybe you have already something in mind :)

cheers

**Comment by MatteoGabriele** [comment]
see 8fddca1

**Comment by MatteoGabriele** [comment]
@wannymiarelli the feature has been added with the 5.7.0

let me know if it works for you!

**Comment by wannymiarelli** [comment]
@MatteoGabriele Wounderful :) more or less what i was thinking about :)
I will test it and report back to you
